FROM node:18

# Create app directory
WORKDIR /usr/src/app

# Install dependencies
COPY package.json ./
RUN npm install

# Copy app source
COPY . .

# Expose port
EXPOSE 3000

CMD ["node", "index.js"]
